- name: deploy k8s worker node
  hosts: worker
  remote_user: ubuntu

  become: yes

  tasks:
    - name: Remove old repository
      file:
        path: /tmp/quickstart-k8s/
        state: absent

    - name: Clone git repository
      git: repo=https://github.com/robertonscjr/quickstart-k8s.git dest=/tmp/quickstart-k8s/

    - name: Setup worker node
      shell: bash /tmp/quickstart-k8s/bootstrap/1-setup_node.sh

    - name: Install docker container engine
      shell: bash /tmp/quickstart-k8s/bootstrap/2-install_docker.sh

    - name: Install k8s tools
      shell: bash /tmp/quickstart-k8s/bootstrap/3-install_kubetools.sh

    - name: Join worker node to k8s cluster
      shell: kubeadm join {{ CONTROL_PLANE_NODE_IP }}:6443 --token {{ TOKEN }} --discovery-token-ca-cert-hash sha256:{{ DISCOVERY_TOKEN_HASH }}
